### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by cchamchi** [maximkulkin/lewansoul-lx16a#2]
Hi I'm trying to install your package on mac(pyhton 2.7)
The following error occurred and same error in ubuntu 18.04(python2.7)

running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating lewansoul_lx16a.egg-info
writing requirements to lewansoul_lx16a.egg-info/requires.txt
writing lewansoul_lx16a.egg-info/PKG-INFO
writing top-level names to lewansoul_lx16a.egg-info/top_level.txt
writing dependency_links to lewansoul_lx16a.egg-info/dependency_links.txt
writing manifest file 'lewansoul_lx16a.egg-info/SOURCES.txt'
reading manifest file 'lewansoul_lx16a.egg-info/SOURCES.txt'
writing manifest file 'lewansoul_lx16a.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-intel/egg
running install_lib
running build_py
creating build
creating build/lib
copying lewansoul_lx16a.py -> build/lib
creating build/bdist.macosx-10.13-intel
creating build/bdist.macosx-10.13-intel/egg
copying build/lib/lewansoul_lx16a.py -> build/bdist.macosx-10.13-intel/egg
byte-compiling build/bdist.macosx-10.13-intel/egg/lewansoul_lx16a.py to lewansoul_lx16a.pyc
  File "build/bdist.macosx-10.13-intel/egg/lewansoul_lx16a.py", line 104
    0x55, 0x55, servo_id, length, command, *params, checksum
                                           ^
SyntaxError: invalid syntax

**Comment by cchamchi** [comment]
I tried in ubuntu with "python3 setup.py install", installation was ok but i cant launch GUI

parallels@ubuntu:~/Desktop/lewansoul-lx16a/lewansoul-lx16a-terminal$ python3 lewansoul_lx16a_terminal.py
parallels@ubuntu:~/Desktop/lewansoul-lx16a/lewansoul-lx16a-terminal$ 

just prompt was returned, No GUI appeared

**Comment by maximkulkin** [comment]
Oh yeah, the application was meant to be run from a script installed during setup process. I have added standalone mode, so now it should work.

**Comment by cchamchi** [comment]
Thank you It works !!
